# Generated by Django 5.0.4 on 2024-11-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lishapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
    ]
